name: to_do_in
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8

  # Firebase
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9

  # Timezone (untuk Google Calendar)
  timezone: ^0.10.1

  # Others
  http: ^1.4.0
  url_launcher: ^6.3.1
  intl: ^0.20.2
  video_player: ^2.10.0
  table_calendar: ^3.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/