// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5xmT_iTicdxx0o4YLtHcp7XEA-Wf0BXk',
    appId: '1:46948739608:web:a03c867cc950ee61c5b16d',
    messagingSenderId: '46948739608',
    projectId: 'todoin-7b9ad',
    authDomain: 'todoin-7b9ad.firebaseapp.com',
    storageBucket: 'todoin-7b9ad.firebasestorage.app',
    measurementId: 'G-997MKG2CFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy1ZU4wdDT9iOcq-lVpNNiiOkK8ztBNq0',
    appId: '1:46948739608:android:4194670c02c2b3adc5b16d',
    messagingSenderId: '46948739608',
    projectId: 'todoin-7b9ad',
    storageBucket: 'todoin-7b9ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB95S6wIjwH3KqYYZYD6aoDbnpxfmV1uHY',
    appId: '1:46948739608:ios:0558ada398c7b4b0c5b16d',
    messagingSenderId: '46948739608',
    projectId: 'todoin-7b9ad',
    storageBucket: 'todoin-7b9ad.firebasestorage.app',
    iosBundleId: 'com.example.toDoIn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB95S6wIjwH3KqYYZYD6aoDbnpxfmV1uHY',
    appId: '1:46948739608:ios:0558ada398c7b4b0c5b16d',
    messagingSenderId: '46948739608',
    projectId: 'todoin-7b9ad',
    storageBucket: 'todoin-7b9ad.firebasestorage.app',
    iosBundleId: 'com.example.toDoIn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5xmT_iTicdxx0o4YLtHcp7XEA-Wf0BXk',
    appId: '1:46948739608:web:159f9cd94f6a47c0c5b16d',
    messagingSenderId: '46948739608',
    projectId: 'todoin-7b9ad',
    authDomain: 'todoin-7b9ad.firebaseapp.com',
    storageBucket: 'todoin-7b9ad.firebasestorage.app',
    measurementId: 'G-C7YZTZ955K',
  );
}
